# SERVER CONFIG
server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /ria-commerce/api

# SPRING CONFIG
spring:
    application:
        name: ria-commerce
    banner:
        location: static/banner.txt
